[package]
name = "minigrep"
version = "0.1.0"
authors = ["arskdj <68353557+arskdj@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
